[tool.black]
target-version = ['py311']
line-length = 79

[tool.isort]
py_version=311
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
skip = '.venv,venv,env,migrations'
src_paths = ["src"]

[tool.pytest.ini_options]
pythonpath = [".", "src"]
asyncio_mode="auto"
