name: Check my Python-FastAPI and javaScript-React.js code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pip install ruff black isort
      - name: Install frontend dependencies
        run: npm install

      - name: Run isort formatter
        run: isort --check ./backend
      - name: Run black formatter
        run: black --check ./backend
      - name: Run linter
        run: ruff ./backend
      - name: Run ESLint
        run: npm run lint
